frr version 10.7
frr defaults traditional
hostname edge-east
log stdout informational
service integrated-vtysh-config
!
interface lo
 description Router ID and test destination
 ip address 10.255.0.4/32
 ip ospf area 0
!
interface eth1
 description Transit to core-a
 ip address 10.0.24.2/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
interface eth2
 description Transit to core-b
 ip address 10.0.34.2/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
router ospf
 ospf router-id 10.255.0.4
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 maximum-paths 2
!
line vty
!
end
